# Generated by Django 5.2.8 on 2025-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngos", "0002_campaign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="description",
            new_name="story",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="campaign_id",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="image_url",
        ),
        migrations.AddField(
            model_name="campaign",
            name="goal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
