# Generated by Django 5.2.8 on 2025-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngos", "0003_rename_description_campaign_story_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="image",
        ),
        migrations.AddField(
            model_name="campaign",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="raised",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
